[project]
name = "docker-tools"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "click>=8.2.1",
    "pydantic>=2.11.5",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
