ruleDirs:
- /home/luiscberrocal/PycharmProjects/docker-tools-plus/rules
testConfigs:
- testDir: /home/luiscberrocal/PycharmProjects/docker-tools-plus/rule-tests
utilDirs:
- /home/luiscberrocal/PycharmProjects/docker-tools-plus/utils
